version: '3'
services:

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    networks:
      - dev-networkss
    volumes:
      - ./assetss/data:/data/db

    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
    #   - MONGO_INITDB_ROOT_PASSWORD=hunter2
  myapplications:
     build: .
     restart: always
     ports:
       - 3000:3000
     depends_on:
       - mongodb
     networks:
       - dev-networkss 

    # environment: 
    #   - MONGODB_CONNSTRING=mongodb://AzureDiamond:hunter2@mongodb
networks:
     dev-networkss:   
        driver: bridge

